[pytest]
asyncio_default_fixture_loop_scope = function
addopts = -v -s --html=reports/report.html --self-contained-html --browser_name=chrome
testpaths = tests
markers =
    smoke: Smoke tests
    regression: Regression tests